name: REUSE Compliance Check

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call: {}

jobs:
  reuse:
    runs-on: [default]
    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v4