name: E2E
on:
  workflow_dispatch: {}

jobs:
  e2e:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        k8s-version: ['v1.30.3','v1.30.4','v1.31.0']
    steps:
      - uses: kengou4/common/workflows/e2e@main
        with:
          kubernetes-version: ${{ matrix.k8s-version }}