name: E2E
on:
  workflow_dispatch: {}

jobs:
  e2e:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: kengou4/common/workflows/e2e@main
        with:
          kubernetes-version: '1.31'
          go-version: '1.23'