name: Check & Fix License Header
on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-license-eye:
    permissions:
      contents: write
    uses: kengou4/common/.github/workflows/play-shared-license.yaml@main
    with:
      apply_header: false
