---
name: Delete closed PR helm chart

"on":
    workflow_dispatch: {}
    pull_request:
        types: [ opened, synchronize, reopened, labeled ]

jobs:
    cleanup-pr-tag:
        if: ${{ github.event.label.name == 'chart-beta' }}
        runs-on: [ default ]
        steps:
        - name: Set image version for PR to branch name
          id: chart-name
          run: |
            echo "VERSION=${GITHUB_REF//\//-}"
            echo ${{ github.event.pull_request.labels }}
